language: generic
env: SWIFT_VERSION=4.1

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx
      osx_image: xcode9.4

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test
