language: generic
env: SWIFT_VERSION=4.2-DEVELOPMENT-SNAPSHOT-2018-08-16-a

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
    - os: osx
      osx_image: xcode10

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift build
  - swift test
